#!/bin/sh

# Переменная для хранения последней раскладки
last_layout=""

while true; do
    # Получаем информацию о клавиатуре с помощью hyprctl
    keyboard_info=$(hyprctl devices | grep -A 4 "Keyboard" | sed -n '18p')

    # Извлекаем текущую раскладку клавиатуры
    current_layout=$(echo "$keyboard_info" | grep "active keymap" | awk '{print $3}')

    # Обрабатываем различные возможные названия раскладок
    case "$current_layout" in
        "English"|"en_US"|"us")
            layout_name="EN";;
        "Russian"|"ru_RU"|"ru")
            layout_name="RU";;
        *)
            layout_name="$current_layout";;
    esac

    # Выводим текущую раскладку, если она изменилась
    if [ "$layout_name" != "$last_layout" ]; then
        echo "$layout_name"
        last_layout="$layout_name"
    fi

    sleep 0.05  # Задержка для снижения нагрузки на CPU
done
